/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package alluxio.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2018-08-08")
public class GetPrefTResponse implements org.apache.thrift.TBase<GetPrefTResponse, GetPrefTResponse._Fields>, java.io.Serializable, Cloneable, Comparable<GetPrefTResponse> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("GetPrefTResponse");

  private static final org.apache.thrift.protocol.TField PREF_FIELD_DESC = new org.apache.thrift.protocol.TField("pref", org.apache.thrift.protocol.TType.MAP, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new GetPrefTResponseStandardSchemeFactory());
    schemes.put(TupleScheme.class, new GetPrefTResponseTupleSchemeFactory());
  }

  public Map<String,Double> pref; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    PREF((short)1, "pref");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // PREF
          return PREF;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.PREF, new org.apache.thrift.meta_data.FieldMetaData("pref", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING), 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(GetPrefTResponse.class, metaDataMap);
  }

  public GetPrefTResponse() {
  }

  public GetPrefTResponse(
    Map<String,Double> pref)
  {
    this();
    this.pref = pref;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public GetPrefTResponse(GetPrefTResponse other) {
    if (other.isSetPref()) {
      Map<String,Double> __this__pref = new HashMap<String,Double>(other.pref);
      this.pref = __this__pref;
    }
  }

  public GetPrefTResponse deepCopy() {
    return new GetPrefTResponse(this);
  }

  @Override
  public void clear() {
    this.pref = null;
  }

  public int getPrefSize() {
    return (this.pref == null) ? 0 : this.pref.size();
  }

  public void putToPref(String key, double val) {
    if (this.pref == null) {
      this.pref = new HashMap<String,Double>();
    }
    this.pref.put(key, val);
  }

  public Map<String,Double> getPref() {
    return this.pref;
  }

  public GetPrefTResponse setPref(Map<String,Double> pref) {
    this.pref = pref;
    return this;
  }

  public void unsetPref() {
    this.pref = null;
  }

  /** Returns true if field pref is set (has been assigned a value) and false otherwise */
  public boolean isSetPref() {
    return this.pref != null;
  }

  public void setPrefIsSet(boolean value) {
    if (!value) {
      this.pref = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case PREF:
      if (value == null) {
        unsetPref();
      } else {
        setPref((Map<String,Double>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case PREF:
      return getPref();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case PREF:
      return isSetPref();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof GetPrefTResponse)
      return this.equals((GetPrefTResponse)that);
    return false;
  }

  public boolean equals(GetPrefTResponse that) {
    if (that == null)
      return false;

    boolean this_present_pref = true && this.isSetPref();
    boolean that_present_pref = true && that.isSetPref();
    if (this_present_pref || that_present_pref) {
      if (!(this_present_pref && that_present_pref))
        return false;
      if (!this.pref.equals(that.pref))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_pref = true && (isSetPref());
    list.add(present_pref);
    if (present_pref)
      list.add(pref);

    return list.hashCode();
  }

  @Override
  public int compareTo(GetPrefTResponse other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetPref()).compareTo(other.isSetPref());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPref()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.pref, other.pref);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("GetPrefTResponse(");
    boolean first = true;

    sb.append("pref:");
    if (this.pref == null) {
      sb.append("null");
    } else {
      sb.append(this.pref);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class GetPrefTResponseStandardSchemeFactory implements SchemeFactory {
    public GetPrefTResponseStandardScheme getScheme() {
      return new GetPrefTResponseStandardScheme();
    }
  }

  private static class GetPrefTResponseStandardScheme extends StandardScheme<GetPrefTResponse> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, GetPrefTResponse struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // PREF
            if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
              {
                org.apache.thrift.protocol.TMap _map8 = iprot.readMapBegin();
                struct.pref = new HashMap<String,Double>(2*_map8.size);
                String _key9;
                double _val10;
                for (int _i11 = 0; _i11 < _map8.size; ++_i11)
                {
                  _key9 = iprot.readString();
                  _val10 = iprot.readDouble();
                  struct.pref.put(_key9, _val10);
                }
                iprot.readMapEnd();
              }
              struct.setPrefIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, GetPrefTResponse struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.pref != null) {
        oprot.writeFieldBegin(PREF_FIELD_DESC);
        {
          oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.DOUBLE, struct.pref.size()));
          for (Map.Entry<String, Double> _iter12 : struct.pref.entrySet())
          {
            oprot.writeString(_iter12.getKey());
            oprot.writeDouble(_iter12.getValue());
          }
          oprot.writeMapEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class GetPrefTResponseTupleSchemeFactory implements SchemeFactory {
    public GetPrefTResponseTupleScheme getScheme() {
      return new GetPrefTResponseTupleScheme();
    }
  }

  private static class GetPrefTResponseTupleScheme extends TupleScheme<GetPrefTResponse> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, GetPrefTResponse struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetPref()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetPref()) {
        {
          oprot.writeI32(struct.pref.size());
          for (Map.Entry<String, Double> _iter13 : struct.pref.entrySet())
          {
            oprot.writeString(_iter13.getKey());
            oprot.writeDouble(_iter13.getValue());
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, GetPrefTResponse struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TMap _map14 = new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.DOUBLE, iprot.readI32());
          struct.pref = new HashMap<String,Double>(2*_map14.size);
          String _key15;
          double _val16;
          for (int _i17 = 0; _i17 < _map14.size; ++_i17)
          {
            _key15 = iprot.readString();
            _val16 = iprot.readDouble();
            struct.pref.put(_key15, _val16);
          }
        }
        struct.setPrefIsSet(true);
      }
    }
  }

}

